FROM node:22-alpine

RUN apk add --no-cache ffmpeg

WORKDIR /app

RUN corepack enable

ENV CI=true
ENV PNPM_CONFIG_DANGEROUSLY_ALLOW_ALL_BUILDS=true

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

CMD ["pnpm","dev"]